### ISSUE TITLE
Error "Exception encountered processing line 0" (Header)

### ISSUE THREAD

**Issue by ttrading** [jcustenborder/kafka-connect-spooldir#128]
I am trying to process a tab delimited file with headers. Following is my config file:

name=messages
tasks.max=2
connector.class=com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector
input.file.pattern=^messages_processed.*\.csv$
finished.path=/var/finished
input.path=/var/sftp/o365
error.path=/var/error
halt.on.error=false
topic=o365
key.schema={"name":"com.example.users.UserKey","type":"STRUCT","isOptional":false,"fieldSchemas":{"Taskid":{"type":"STRING","isOptional":false}}}
value.schema={"name":"com.example.users.User","type":"STRUCT","isOptional":false,"fieldSchemas":{"AffectedWorkloadDisplayNames":{"type":"STRING","isOptional":true},"AffectedWorkloadNames":{"type":"STRING","isOptional":true},"Status":{"type":"STRING","isOptional":true},"Workload":{"type":"STRING","isOptional":true},"WorkloadDisplayName":{"type":"STRING","isOptional":true},"ActionType":{"type":"STRING","isOptional":true},"AffectedTenantCount":{"type":"INT64","isOptional":true},"AffectedUserCount":{"type":"INT64","isOptional":true},"Classification":{"type":"STRING","isOptional":true},"EndTime":{"type":"STRING","isOptional":true},"Feature":{"type":"STRING","isOptional":true},"FeatureDisplayName":{"type":"STRING","isOptional":true},"UserFunctionalImpact":{"type":"STRING","isOptional":true},"Id":{"type":"STRING","isOptional":true},"ImpactDescription":{"type":"STRING","isOptional":true},"LastUpdatedTime":{"type":"STRING","isOptional":true},"MessageType":{"type":"STRING","isOptional":true},"PostIncidentDocumentUrl":{"type":"STRING","isOptional":true},"Severity":{"type":"STRING","isOptional":true},"StartTime":{"type":"STRING","isOptional":true},"Title":{"type":"STRING","isOptional":true},"Taskid":{"type":"STRING","isOptional":true},"Hostname":{"type":"STRING","isOptional":true},"Taskname":{"type":"STRING","isOptional":true},"Timestamp":{"type":"INT64","isOptional":true}}}
csv.first.row.as.header=true
csv.separator.char=9

The system is constantly complaining about not being able to process line 0. I opened the failed files and checked them manually. The structure of the file seems to be ok. What could be wrong?

Thanks,

[2020-04-14 17:24:01,455] ERROR Exception encountered processing line 0 of /var/sftp/o365/messages_processed_1586885016958195426.csv. (com.github.jcustenborder.kafka.connect.spooldir.AbstractSourceTask:260)
org.apache.kafka.connect.errors.ConnectException: java.lang.NullPointerException
        at com.github.jcustenborder.kafka.connect.spooldir.AbstractSourceTask.read(AbstractSourceTask.java:251)
        at com.github.jcustenborder.kafka.connect.spooldir.AbstractSourceTask.poll(AbstractSourceTask.java:149)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:265)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:232)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at java.util.Arrays$ArrayList.<init>(Arrays.java:3813)
        at java.util.Arrays.asList(Arrays.java:3800)
        at com.google.common.base.Joiner.join(Joiner.java:203)
        at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceTask.configure(SpoolDirCsvSourceTask.java:62)
        at com.github.jcustenborder.kafka.connect.spooldir.AbstractSourceTask.read(AbstractSourceTask.java:249)
        ... 10 more
[2020-04-14 17:24:01,455] ERROR Error during processing, moving /var/sftp/o365/messages_processed_1586885016958195426.csv to /var/error. (com.github.jcustenborder.kafka.connect.spooldir.AbstractCleanUpPolicy:92)
[2020-04-14 17:24:01,456] INFO Moving /var/sftp/o365/messages_processed_1586885016958195426.csv to /var/error/messages_processed_1586885016958195426.csv (com.github.jcustenborder.kafka.connect.spooldir.InputFile:152)

**Comment by jcustenborder** [comment]
@ttrading What version is this?

**Comment by ttrading** [comment]
2.0.43

**Comment by jcustenborder** [comment]
Is the delimiter correct? Here is the line that is failing. It's basically not getting anything back from the header. 

https://github.com/jcustenborder/kafka-connect-spooldir/blob/master/src/main/java/com/github/jcustenborder/kafka/connect/spooldir/SpoolDirCsvSourceTask.java#L62

**Comment by ttrading** [comment]
Here is the file that I located under the error folder:
[messages_processed_1586885016958195426.txt](https://github.com/jcustenborder/kafka-connect-spooldir/files/4476797/messages_processed_1586885016958195426.txt)

The header is in place. I am not sure what happened.

**Comment by ttrading** [comment]
What is the separator code for pipe character? "|"

Wiki mentions 44 for comma and 9 for tab.

**Comment by jcustenborder** [comment]
According to the [Ascii table](http://www.asciitable.com/) 124.

**Comment by ttrading** [comment]
thanks...That did not help the situation. The file is still place under the error folder.

My config has the following two items:
csv.first.row.as.header=true
csv.separator.char=124

[messages_processed_1586886481221855423.txt](https://github.com/jcustenborder/kafka-connect-spooldir/files/4476862/messages_processed_1586886481221855423.txt)

**Comment by jcustenborder** [comment]
Interestingly enough. I get a different error message using your original config. 

```text
[2020-04-14 12:54:22,440] ERROR Exception encountered processing line 2 of /tmp/spooldir/input/messages_processed_1586885016958195426.txt. (com.github.jcustenborder.kafka.connect.spooldir.AbstractSourceTask:260)
org.apache.kafka.connect.errors.DataException: Exception thrown while parsing data for 'AffectedUserCount'. linenumber=2
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceTask.process(SpoolDirCsvSourceTask.java:133)
	at com.github.jcustenborder.kafka.connect.spooldir.AbstractSourceTask.read(AbstractSourceTask.java:256)
	at com.github.jcustenborder.kafka.connect.spooldir.AbstractSourceTask.poll(AbstractSourceTask.java:149)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:245)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:221)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: Could not parse '' to 'Long'
	at com.github.jcustenborder.kafka.connect.utils.data.Parser.parseString(Parser.java:113)
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceTask.process(SpoolDirCsvSourceTask.java:125)
	... 11 more
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:601)
	at java.lang.Long.parseLong(Long.java:631)
	at com.github.jcustenborder.kafka.connect.utils.data.type.Int64TypeParser.parseString(Int64TypeParser.java:24)
	at com.github.jcustenborder.kafka.connect.utils.data.Parser.parseString(Parser.java:109)
	... 12 more
```

**Comment by ttrading** [comment]
Do you think this is a field type mismatch issue? Or issue with handling the empty fields?

**Comment by jcustenborder** [comment]
Give this config a try. I changed [csv.null.field.indicator=BOTH](https://jcustenborder.github.io/kafka-connect-documentation/projects/kafka-connect-spooldir/sources/SpoolDirCsvSourceConnector.html#csv-null-field-indicator)

```properties
name=messages
tasks.max=2
connector.class=com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector
input.file.pattern=^messages_processed.*.txt$
finished.path=/tmp/spooldir/finished
input.path=/tmp/spooldir/input
error.path=/tmp/spooldir/error
halt.on.error=false
topic=o365
key.schema={"name":"com.example.users.UserKey","type":"STRUCT","isOptional":false,"fieldSchemas":{"Taskid":{"type":"STRING","isOptional":false}}}
value.schema={"name":"com.example.users.User","type":"STRUCT","isOptional":false,"fieldSchemas":{"AffectedWorkloadDisplayNames":{"type":"STRING","isOptional":true},"AffectedWorkloadNames":{"type":"STRING","isOptional":true},"Status":{"type":"STRING","isOptional":true},"Workload":{"type":"STRING","isOptional":true},"WorkloadDisplayName":{"type":"STRING","isOptional":true},"ActionType":{"type":"STRING","isOptional":true},"AffectedTenantCount":{"type":"INT64","isOptional":true},"AffectedUserCount":{"type":"INT64","isOptional":true},"Classification":{"type":"STRING","isOptional":true},"EndTime":{"type":"STRING","isOptional":true},"Feature":{"type":"STRING","isOptional":true},"FeatureDisplayName":{"type":"STRING","isOptional":true},"UserFunctionalImpact":{"type":"STRING","isOptional":true},"Id":{"type":"STRING","isOptional":true},"ImpactDescription":{"type":"STRING","isOptional":true},"LastUpdatedTime":{"type":"STRING","isOptional":true},"MessageType":{"type":"STRING","isOptional":true},"PostIncidentDocumentUrl":{"type":"STRING","isOptional":true},"Severity":{"type":"STRING","isOptional":true},"StartTime":{"type":"STRING","isOptional":true},"Title":{"type":"STRING","isOptional":true},"Taskid":{"type":"STRING","isOptional":true},"Hostname":{"type":"STRING","isOptional":true},"Taskname":{"type":"STRING","isOptional":true},"Timestamp":{"type":"INT64","isOptional":true}}}
csv.first.row.as.header=true
csv.separator.char=9
csv.null.field.indicator=BOTH
```

**Comment by ttrading** [comment]
I was just about to send you a message :) Yes that works. I tried:
csv.null.field.indicator=EMPTY_SEPARATORS

Thanks for the help

**Comment by jcustenborder** [comment]
NP! Glad you got it working.

**Comment by ttrading** [comment]
I think I was a little fast. Here is the issue. When I start the kafka process on the CLI, it imports all the files in input folder to kafka but nothing loaded in the input file after that gets processed. They are placed in the error folder. Here is my config file:


finished.path=/var/o365_finished
input.path=/var/sftp/o365
error.path=/var/o365_error
halt.on.error=false
topic=o365
key.schema={"name":"com.example.users.UserKey","type":"STRUCT","isOptional":false,"fieldSchemas":{"Taskid":{"type":"STRING","isOptional":false}}}
value.schema={"name":"com.example.users.User","type":"STRUCT","isOptional":false,"fieldSchemas":{"AffectedWorkloadDisplayNames":{"type":"STRING","isOptional":true},"AffectedWorkloadNames":{"type":"STRING","isOptional":true},"Status":{"type":"STRING","isOptional":true},"Workload":{"type":"STRING","isOptional":true},"WorkloadDisplayName":{"type":"STRING","isOptional":true},"ActionType":{"type":"STRING","isOptional":true},"AffectedTenantCount":{"type":"INT64","isOptional":true},"AffectedUserCount":{"type":"INT64","isOptional":true},"Classification":{"type":"STRING","isOptional":true},"EndTime":{"type":"STRING","isOptional":true},"Feature":{"type":"STRING","isOptional":true},"FeatureDisplayName":{"type":"STRING","isOptional":true},"UserFunctionalImpact":{"type":"STRING","isOptional":true},"Id":{"type":"STRING","isOptional":true},"ImpactDescription":{"type":"STRING","isOptional":true},"LastUpdatedTime":{"type":"STRING","isOptional":true},"MessageType":{"type":"STRING","isOptional":true},"PostIncidentDocumentUrl":{"type":"STRING","isOptional":true},"Severity":{"type":"STRING","isOptional":true},"StartTime":{"type":"STRING","isOptional":true},"Title":{"type":"STRING","isOptional":true},"Taskid":{"type":"STRING","isOptional":false},"Hostname":{"type":"STRING","isOptional":true},"Taskname":{"type":"STRING","isOptional":true},"Timestamp":{"type":"INT64","isOptional":true}}}
csv.first.row.as.header=true
csv.separator.char=124
csv.null.field.indicator=BOTH

Following is a sample error file:
[messages_processed_1586890142000714049.txt](https://github.com/jcustenborder/kafka-connect-spooldir/files/4477161/messages_processed_1586890142000714049.txt)

I am using | as the delimiter and before sending it to input folder, I use sed to tweak the CSV and fill up the empty fields with 0.

Still no luck.

**Comment by jcustenborder** [comment]
I guess I don't understand why you're hitting it with sed? Is this a different file format? I was able to read your last example.

**Comment by ttrading** [comment]
I figured if I fill up all the fields with a default value (in this case 0) I rule out some of the potential issues I might run into. I can take sed out of the picture and just send the CSV as it is.

**Comment by jcustenborder** [comment]
The connector can handle empty fields and it handles it as a tsv. Have you tried the config I posted earlier? That read your sample file

**Comment by ttrading** [comment]
I did. I switched back to tab delimited on my data source and removed sed from my shell script. So now I am pushing a tab limited file and processing it with the config file you provided. The result is the same. Whatever that is already in the input folder is processed successfully first time I start kafka-connect and pushed to Kafka. However, any subsequent file is placed in the error folder. Following is a file that gave me the error:

[messages_processed_1586894341260835146.txt](https://github.com/jcustenborder/kafka-connect-spooldir/files/4477471/messages_processed_1586894341260835146.txt)

I am sending you another file here so that you can try to load it after you start your kafka-connect. I am curious if you will get the same result.
[messages_processed_1586894630034053547.zip](https://github.com/jcustenborder/kafka-connect-spooldir/files/4477479/messages_processed_1586894630034053547.zip)

Here is the error:

[2020-04-14 20:03:14,955] INFO Creating processing flag /var/sftp/o365/messages_processed_1586894581093391832.csv.PROCESSING (com.github.jcustenborder.kafka.connect.spooldir.InputFile:107)
[2020-04-14 20:03:14,955] INFO Opening /var/sftp/o365/messages_processed_1586894581093391832.csv (com.github.jcustenborder.kafka.connect.spooldir.AbstractSourceTask:237)
[2020-04-14 20:03:14,956] ERROR Exception encountered processing line 0 of /var/sftp/o365/messages_processed_1586894581093391832.csv. (com.github.jcustenborder.kafka.connect.spooldir.AbstractSourceTask:260)
org.apache.kafka.connect.errors.ConnectException: java.lang.NullPointerException
        at com.github.jcustenborder.kafka.connect.spooldir.AbstractSourceTask.read(AbstractSourceTask.java:251)
        at com.github.jcustenborder.kafka.connect.spooldir.AbstractSourceTask.poll(AbstractSourceTask.java:149)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:265)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:232)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at java.util.Arrays$ArrayList.<init>(Arrays.java:3813)
        at java.util.Arrays.asList(Arrays.java:3800)
        at com.google.common.base.Joiner.join(Joiner.java:203)
        at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceTask.configure(SpoolDirCsvSourceTask.java:62)
        at com.github.jcustenborder.kafka.connect.spooldir.AbstractSourceTask.read(AbstractSourceTask.java:249)
        ... 10 more
[2020-04-14 20:03:14,956] ERROR Error during processing, moving /var/sftp/o365/messages_processed_1586894581093391832.csv to /var/o365_error. (com.github.jcustenborder.kafka.connect.spooldir.AbstractCleanUpPolicy:92)
[2020-04-14 20:03:14,956] INFO Moving /var/sftp/o365/messages_processed_1586894581093391832.csv to /var/o365_error/messages_processed_1586894581093391832.csv (com.github.jcustenborder.kafka.connect.spooldir.InputFile:152)
[2020-04-14 20:03:15,329] INFO No files matching input.file.pattern were found in /var/sftp/o365 (com.github.jcustenborder.kafka.connect.spooldir.InputFileDequeue:63)
[2020-04-14 20:03:15,329] INFO No files matching input.file.pattern were found in /var/sftp/mtr (com.github.jcustenborder.kafka.connect.spooldir.InputFileDequeue:63)
[2020-04-14 20:03:15,329] INFO No files matching input.file.pattern were found in /var/sftp/o365 (com.github.jcustenborder.kafka.connect.spooldir.InputFileDequeue:63)
[2020-04-14 20:03:15,329] INFO No files matching input.file.pattern were found in /var/sftp/mtr (com.github.jcustenborder.kafka.connect.spooldir.InputFileDequeue:63)
[2020-04-14 20:03:15,330] INFO No files matching input.file.pattern were found in /var/sftp/o365 (com.github.jcustenborder.kafka.connect.spooldir.InputFileDequeue:63)

**Comment by jcustenborder** [comment]
```properties
name=messages
tasks.max=2
connector.class=com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector
input.file.pattern=^messages_processed.*.csv$
finished.path=/tmp/spooldir/finished
input.path=/tmp/spooldir/input
error.path=/tmp/spooldir/error
halt.on.error=false
topic=o365
key.schema={"name":"com.example.users.UserKey","type":"STRUCT","isOptional":false,"fieldSchemas":{"Taskid":{"type":"STRING","isOptional":false}}}
value.schema={"name":"com.example.users.User","type":"STRUCT","isOptional":false,"fieldSchemas":{"AffectedWorkloadDisplayNames":{"type":"STRING","isOptional":true},"AffectedWorkloadNames":{"type":"STRING","isOptional":true},"Status":{"type":"STRING","isOptional":true},"Workload":{"type":"STRING","isOptional":true},"WorkloadDisplayName":{"type":"STRING","isOptional":true},"ActionType":{"type":"STRING","isOptional":true},"AffectedTenantCount":{"type":"INT64","isOptional":true},"AffectedUserCount":{"type":"INT64","isOptional":true},"Classification":{"type":"STRING","isOptional":true},"EndTime":{"type":"STRING","isOptional":true},"Feature":{"type":"STRING","isOptional":true},"FeatureDisplayName":{"type":"STRING","isOptional":true},"UserFunctionalImpact":{"type":"STRING","isOptional":true},"Id":{"type":"STRING","isOptional":true},"ImpactDescription":{"type":"STRING","isOptional":true},"LastUpdatedTime":{"type":"STRING","isOptional":true},"MessageType":{"type":"STRING","isOptional":true},"PostIncidentDocumentUrl":{"type":"STRING","isOptional":true},"Severity":{"type":"STRING","isOptional":true},"StartTime":{"type":"STRING","isOptional":true},"Title":{"type":"STRING","isOptional":true},"Taskid":{"type":"STRING","isOptional":true},"Hostname":{"type":"STRING","isOptional":true},"Taskname":{"type":"STRING","isOptional":true},"Timestamp":{"type":"INT64","isOptional":true}}}
csv.first.row.as.header=true
csv.separator.char=9
csv.null.field.indicator=BOTH
```

Yielded this

```text
[2020-04-14 15:08:30,601] INFO Finished processing 153 record(s) in 1 second(s). Processing speed 63.5 KiB per second. (com.github.jcustenborder.kafka.connect.spooldir.AbstractSourceTask:194)
[2020-04-14 15:08:30,602] INFO Closing /tmp/spooldir/input/messages_processed_1586894630034053547.csv (com.github.jcustenborder.kafka.connect.spooldir.InputFile:121)
[2020-04-14 15:08:30,602] INFO Removing processing flag /tmp/spooldir/input/messages_processed_1586894630034053547.csv.PROCESSING (com.github.jcustenborder.kafka.connect.spooldir.InputFile:125)
[2020-04-14 15:08:30,602] INFO Moving /tmp/spooldir/input/messages_processed_1586894630034053547.csv to /tmp/spooldir/finished/messages_processed_1586894630034053547.csv (com.github.jcustenborder.kafka.connect.spooldir.InputFile:152)
[2020-04-14 15:08:30,608] INFO Creating processing flag /tmp/spooldir/input/messages_processed_1586894641464540808.csv.PROCESSING (com.github.jcustenborder.kafka.connect.spooldir.InputFile:107)
[2020-04-14 15:08:30,609] INFO Opening /tmp/spooldir/input/messages_processed_1586894641464540808.csv (com.github.jcustenborder.kafka.connect.spooldir.AbstractSourceTask:237)
[2020-04-14 15:08:30,610] INFO configure() - field names from header row. fields = AffectedWorkloadDisplayNames, AffectedWorkloadNames, Status, Workload, WorkloadDisplayName, ActionType, AffectedTenantCount, AffectedUserCount, Classification, EndTime, Feature, FeatureDisplayName, UserFunctionalImpact, Id, ImpactDescription, LastUpdatedTime, MessageType, PostIncidentDocumentUrl, Severity, StartTime, Title, Taskid, Hostname, Taskname, Timestamp (com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceTask:62)
[2020-04-14 15:08:30,676] INFO Finished processing 153 record(s) in 0 second(s). (com.github.jcustenborder.kafka.connect.spooldir.AbstractSourceTask:201)
[2020-04-14 15:08:30,676] INFO Closing /tmp/spooldir/input/messages_processed_1586894641464540808.csv (com.github.jcustenborder.kafka.connect.spooldir.InputFile:121)
[2020-04-14 15:08:30,676] INFO Removing processing flag /tmp/spooldir/input/messages_processed_1586894641464540808.csv.PROCESSING (com.github.jcustenborder.kafka.connect.spooldir.InputFile:125)
[2020-04-14 15:08:30,677] INFO Moving /tmp/spooldir/input/messages_processed_1586894641464540808.csv to /tmp/spooldir/finished/messages_processed_1586894641464540808.csv (com.github.jcustenborder.kafka.connect.spooldir.InputFile:152)
```

**Comment by jcustenborder** [comment]
What operating system are you running on? I'm testing this on a mac.

**Comment by ttrading** [comment]
CentOS 7.7

**Comment by jcustenborder** [comment]
Unless it's something specific to /var/sftp/o365/messages_processed_1586894581093391832.csv or does this happen to every file you try?

**Comment by ttrading** [comment]
this same issue seems to be happening with this specific file constantly. I have a couple of more CSV file structures to pull some metrics from the monitored system. They seems to be working better. They do experience the same issue intermittently. I say every 1 file out of 10 is placed in the error folder. I ignored the issue so far since the loss rate was not significant but with this file it is 100%.

**Comment by jcustenborder** [comment]
The problem is we haven't reproduced the errors with the data you've given me.

**Comment by ttrading** [comment]
I will build 2.0.43 again and give it a shot.

**Comment by jcustenborder** [comment]
just pointing it out. You've never uploaded messages_processed_1586894581093391832.csv. If this file is somehow different I don't know

**Comment by ttrading** [comment]
I think I will give up on this for now. I am running this to import two separate CSV files:

CLASSPATH=/home/kafka-connect-spooldir-2.0.43/target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-spooldir/* /home/kafka/bin/connect-standalone.sh /home/kafka-connect-spooldir-2.0.43/config/standalone-config.properties /home/kafka-connect-spooldir-2.0.43/config_o365_currentservicestatus/source-o365-currentservicestatus.properties /home/kafka-connect-spooldir-2.0.43/config_o365_messages/source-o365-messages.properties

Current situation is as follows: source-o365-currentservicestatus.properties is set for a comma separated file and works fine. source-o365-messages.properties is set for TAB delimited and failing.

**Comment by jcustenborder** [comment]
I cannot help you without seeing the data in the file or the configuration. All of the ones you have sent me so far have been workable. Unless I repro the issue I cannot be of much help. I would look at the file with a hex editor and ensure that the delimiter is what you think it is

**Comment by ttrading** [comment]
fair enough. I just need to finish a few tasks pending; I will get back to this afterwards.

Thanks for the help.
