### ISSUE TITLE
Date Time Parse Error...

### ISSUE THREAD

**Issue by QuidneIT** [jcustenborder/kafka-connect-spooldir#207]
I am trying to read a CSV file in to Kafka. 
The file looks like this:
```
"Occurrence Time","Event Source","Event Type","Card Number"
"25/11/2022 09:00:10","Bla Bla","Bla Bla","123456"
```

My spooldir json file looks a bit like this:

```
    "connector.class": "com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector",
    "csv.first.row.as.header": "true",
    "schema.generation.enabled": "false",
    "csv.null.field.indicator": "BOTH",
    "csv.ignore.quotations": "true",

    "timestamp.mode": "FILE_TIME",
    "timestamp.field": "Occurrence Time",
    "parser.timestamp.date.formats": "[dd/MM/yyyy HH:mm:ss]",
```

When parsing I get this error:
```
Caused by: org.apache.kafka.connect.errors.DataException: Could not parse '25/11/2022 09:00:10' to 'Date'
        at com.github.jcustenborder.kafka.connect.utils.data.Parser.parseString(Parser.java:113)
        at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceTask.process(SpoolDirCsvSourceTask.java:128)

```

Any idea what I need to do to correct the error?

**Comment by QuidneIT** [comment]
Problem resolved.

Should be:     `"parser.timestamp.date.formats": "dd/MM/yyyy HH:mm:ss",`
