### ISSUE TITLE
SpoolDirCsvSourceConnector: Missing depedency 

### ISSUE THREAD

**Issue by AyoubOm** [jcustenborder/kafka-connect-spooldir#214]
Hello, I am trying to use SpoolDirCsvSourceConnector connector. The following error message appears in the logs when Kafka-connect is scanning for plugins. When POSTing a SpoolDirCsvSourceConnector connector configuration, I receive an error saying the plugin is not available. Please find below the error from kafka-connect logs:

```
ERROR Failed to discover SourceConnector in jcustenborder-kafka-connect-spooldir-2.0.65/lib/kafka-connect-spooldir-2.0.65.jar: Unable to instantiate SpoolDirCsvSourceConnector: Plugin class has a dependency which is missing or invalid (org.apache.kafka.connect.runtime.isolation.ReflectionScanner:138)
java.lang.NoClassDefFoundError: com/google/common/collect/Multimap
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
	at java.base/java.lang.Class.getConstructor0(Class.java:3578)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754)
	at org.apache.kafka.connect.runtime.isolation.ReflectionScanner.versionFor(ReflectionScanner.java:73)
	at org.apache.kafka.connect.runtime.isolation.ReflectionScanner.getPluginDesc(ReflectionScanner.java:136)
	at org.apache.kafka.connect.runtime.isolation.ReflectionScanner.scanPlugins(ReflectionScanner.java:88)
	at org.apache.kafka.connect.runtime.isolation.PluginScanner.scanUrlsAndAddPlugins(PluginScanner.java:79)
	at org.apache.kafka.connect.runtime.isolation.PluginScanner.discoverPlugins(PluginScanner.java:67)
	at org.apache.kafka.connect.runtime.isolation.Plugins.initLoaders(Plugins.java:91)
	at org.apache.kafka.connect.runtime.isolation.Plugins.<init>(Plugins.java:75)
	at org.apache.kafka.connect.runtime.isolation.Plugins.<init>(Plugins.java:64)
	at org.apache.kafka.connect.cli.AbstractConnectCli.startConnect(AbstractConnectCli.java:121)
	at org.apache.kafka.connect.cli.AbstractConnectCli.run(AbstractConnectCli.java:94)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:112)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Multimap
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:124)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 15 more
```

**Comment by AyoubOm** [comment]
Exporting a CLASSPATH variable with plugin jars directory fixed the issue for me
`export CLASSPATH=/path/to/plugin/jars/*`
