### ISSUE TITLE
Connector support pipe delimiter

### ISSUE THREAD

**Issue by anuhewa** [jcustenborder/kafka-connect-spooldir#38]
This connector supports " | " delimiter ?

ex:- file like below

mobile|imsi|2050160|2|14|2|xxxxxx|20160917|vvvvvv|20370101|bbbbbbbbb|1250158,1104006,1210003,xxxxxx,1106000,44444444,1103001|2000:14,3000:-4444444|

Kindly confirm

**Comment by jcustenborder** [comment]
set `csv.separator.char=|`

**Comment by anuhewa** [comment]
Thanks for confirmation.

Any idea on below error 



[2018-02-08 04:46:02,648] ERROR WorkerSourceTask{id=CsvSpoolDir-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:172)
org.apache.kafka.connect.errors.DataException: testing
        at io.confluent.connect.avro.AvroConverter.fromConnectData(AvroConverter.java:77)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:219)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:187)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
Caused by: java.net.MalformedURLException: no protocol: ip:8083/subjects/testing-key/versions
        at java.net.URL.<init>(URL.java:593)
        at java.net.URL.<init>(URL.java:490)
        at java.net.URL.<init>(URL.java:439)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:141)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:218)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:307)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:299)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:294)
        at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.registerAndGetId(CachedSchemaRegistryClient.java:61)
        at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:100)
        at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:79)
        at io.confluent.connect.avro.AvroConverter$Serializer.serialize(AvroConverter.java:110)
        at io.confluent.connect.avro.AvroConverter.fromConnectData(AvroConverter.java:75)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:219)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:187)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by anuhewa** [comment]
my configs as below

[root@host config]# cat connect-avro-docker.properties


bootstrap.servers=ip:9092,ip2:9092
key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=ip:8083
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=ip:8083
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
offset.storage.file.filename=/tmp/connect.offsets
plugin.path=target/kafka-connect-target/usr/share/java
sasl.kerberos.service.name=kafka
security.protocol=SASL_PLAINTEXT
producer.security.protocol=SASL_PLAINTEXT
producer.sasl.kerberos.service.name=kafka
sasl.kerberos.service.name=kafka




==================================================



[root@host config]# cat CSVExample.properties


name=CsvSpoolDir
tasks.max=1
connector.class=com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector
input.file.pattern=^.*\.csv$
finished.path=/tmp/spooldir/finished
halt.on.error=false
topic=testing
key.schema={"name":"com.example.users.UserKey","type":"STRUCT","isOptional":false,"fieldSchemas":{"id":{"type":"INT64","isOptional":false}}}
value.schema={"name":"com.example.users.User","type":"STRUCT","isOptional":false,"fieldSchemas":{"id":{"type":"INT64","isOptional":false},"first_name":{"type":"STRING","isOptional":true},"last_name":{"type":"STRING","isOptional":true},"email":{"type":"STRING","isOptional":true},"gender":{"type":"STRING","isOptional":true},"ip_address":{"type":"STRING","isOptional":true},"last_login":{"name":"org.apache.kafka.connect.data.Timestamp","type":"INT64","version":1,"isOptional":true},"account_balance":{"name":"org.apache.kafka.connect.data.Decimal","type":"BYTES","version":1,"parameters":{"scale":"2"},"isOptional":true},"country":{"type":"STRING","isOptional":true},"favorite_color":{"type":"STRING","isOptional":true}}}
csv.first.row.as.header=true
error.path=/datan1/spool/error/
input.path=/datan1/spool/kafka-connect-spooldir-master/src/test/resources/com/github/jcustenborder/kafka/connect/spooldir/csv/




=============================================================





i executed as below

/datan1/confluent/confluent-4.0.0/bin/connect-standalone config/connect-avro-docker.properties config/CSVExample.properties

**Comment by anuhewa** [comment]
giving below error after changing to pipe


[2018-02-08 06:20:47,142] INFO Started o.e.j.s.ServletContextHandler@34614215{/,null,AVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler:744)
[2018-02-08 06:20:47,164] INFO Started ServerConnector@643d3d72{HTTP/1.1}{0.0.0.0:8083} (org.eclipse.jetty.server.ServerConnector:266)
[2018-02-08 06:20:47,164] INFO Started @8348ms (org.eclipse.jetty.server.Server:379)
[2018-02-08 06:20:47,166] INFO REST server listening at http://ip.xx:8083/, advertising URL http://ip.xx:8083/ (org.apache.kafka.connect.runtime.rest.RestServer:150)
[2018-02-08 06:20:47,166] INFO Kafka Connect started (org.apache.kafka.connect.runtime.Connect:55)
[2018-02-08 06:20:47,186] ERROR Failed to create job for config/CSVExample.properties (org.apache.kafka.connect.cli.ConnectStandalone:97)
[2018-02-08 06:20:47,187] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:108)
java.util.concurrent.ExecutionException: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector configuration is invalid and contains the following 1 error(s):
Invalid value  for configuration csv.separator.char: Not a number of type INT
You can also find the above list of errors at the endpoint `/{connectorType}/config/validate`
        at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:79)
        at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:66)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:105)
Caused by: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector configuration is invalid and contains the following 1 error(s):
Invalid value  for configuration csv.separator.char: Not a number of type INT
You can also find the above list of errors at the endpoint `/{connectorType}/config/validate`
        at org.apache.kafka.connect.runtime.AbstractHerder.maybeAddConfigErrors(AbstractHerder.java:386)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:163)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:102)
[2018-02-08 06:20:47,189] INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect:65)
[2018-02-08 06:20:47,189] INFO Stopping REST server (org.apache.kafka.connect.runtime.rest.RestServer:154)
point `/{connectorType}/config/validate`
        at org.apache.kafka.connect.runtime.AbstractHerder.maybeAddConfigErrors(AbstractHerder.java:386)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:163)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:102)
[2018-02-08 06:20:47,189] INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect:65)
[2018-02-08 06:20:47,189] INFO Stopping REST server (org.apache.kafka.connect.runtime.rest.RestServer:154)

**Comment by anuhewa** [comment]
when I use “csv.separator.char=| “   I am getting  below error ?






Invalid value | for configuration csv.separator.char: Not a number of type INT
You can also find the above list of errors at the endpoint `/{connectorType}/config/validate`
        at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:79)
        at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:66)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:105)
Caused by: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector configuration is invalid and contains the following 1 error(s):
Invalid value | for configuration csv.separator.char: Not a number of type INT
You can also find the above list of errors at the endpoint `/{connectorType}/config/validate`
        at org.apache.kafka.connect.runtime.AbstractHerder.maybeAddConfigErrors(AbstractHerder.java:386)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:163)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:102)
[2018-02-08 08:38:36,158] INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Co

**Comment by Chintanvpatel** [comment]
Hello @anuhewa 

You have to provide ASCII value for "|" character.

**Comment by jcustenborder** [comment]
@anuhewa Try `csv.separator.char=124`
