### ISSUE TITLE
Extended ASCII charcters not allowed as separators

### ISSUE THREAD

**Issue by FWDVladM** [jcustenborder/kafka-connect-spooldir#59]
Character 254 not allowed/ignored as separator (it appears that any character with ASCII code above 127 is getting ignored and results in error:

org.apache.kafka.connect.errors.ConnectException: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirSourceTask.read(SpoolDirSourceTask.java:298)
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirSourceTask.poll(SpoolDirSourceTask.java:165)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:179)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceTask.process(SpoolDirCsvSourceTask.java:111)
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirSourceTask.read(SpoolDirSourceTask.java:286)

**Comment by jcustenborder** [comment]
If you want to give this an additional try with the new RFC8140 support this might help. Try setting `csv.rfc.4180.parser.enabled=true`. If this is still an issue please reopen
