### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/kafka/connect/header/Header

### ISSUE THREAD

**Issue by sharafula** [jcustenborder/kafka-connect-spooldir#61]
Hello when I start the connector I get the following error:

`java.lang.NoClassDefFoundError: org/apache/kafka/connect/header/Header
	at com.github.jcustenborder.kafka.connect.utils.jackson.HeaderSerializationModule.<init>(HeaderSerializationModule.java:37)
	at com.github.jcustenborder.kafka.connect.utils.jackson.ObjectMapperFactory.<clinit>(ObjectMapperFactory.java:36)
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirSourceConnectorConfig.readSchema(SpoolDirSourceConnectorConfig.java:550)
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirSourceConnectorConfig.<init>(SpoolDirSourceConnectorConfig.java:188)
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnectorConfig.<init>(SpoolDirCsvSourceConnectorConfig.java:113)
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector.config(SpoolDirCsvSourceConnector.java:31)
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector.config(SpoolDirCsvSourceConnector.java:25)
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirSourceConnector.start(SpoolDirSourceConnector.java:56)
	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:108)
	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:133)
	at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:192)
	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:211)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:894)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1300(DistributedHerder.java:108)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$15.call(DistributedHerder.java:910)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$15.call(DistributedHerder.java:906)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.connect.header.Header
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
`

Any ideas what I am missing?

**Comment by jcustenborder** [comment]
@sharafula This has been compiled against a later version of the Kafka Connect api. You should use a newer connect worker.

**Comment by tmanipra** [comment]
Hi, I have complied the latest code from Repo using Maven but still I'm getting 

java.lang.NoClassDefFoundError: org/apache/kafka/connect/header/Header 

Could you please advise? Thanks

**Comment by jcustenborder** [comment]
@tmanipra  What version of Apache Kafka are you running this with?

**Comment by tmanipra** [comment]
Apache kafka Version - 2.11-2.3.2

I'm trying to integrate Spooldir with Cloudera Kafka using manual installation without Confluent. 

So, I have downloaded Zip File from Confluent and have moved to Linux Env. Then, Updated the connect-standalone.sh for plugin.path with Spooldir Lib path. 

Upon initiating connect-standalone with CSVExample.properties(Updated with Topic, Input path, Processed path etc):

Im getting java.lang.NoClassDefFoundError: org/apache/kafka/connect/header/Header Error.

**Comment by jcustenborder** [comment]
Disclaimer I do work for Confluent but this plugin is not dependent upon anything from Confluent. Are you editing connect-standalone.sh? If so that could be part of your problem. `plugin.path` is configured in connect-standalone.properties. You should treat `connect-standalone.sh` and the stuff installed by cloudera manager as readonly. (Used to work for Cloudera as well) 

`plugin.path` should point to a directory that holds all your plugins. The directory structure should look something like this. 

```
plugins
+--kafka-connect-spooldir
+--+--lib
+--+--+--something.jar
+--next-plugin
```
