### ISSUE TITLE
<<Exception in thread "main" java.lang.NoClassDefFoundError>> when I try to start kafka connect

### ISSUE THREAD

**Issue by eksantrik** [jcustenborder/kafka-connect-spooldir#63]
Hello,

I downloaded kafka-connect-spooldir-1.0.31 (https://github.com/jcustenborder/kafka-connect-spooldir/releases/download/1.0.31/kafka-connect-spooldir-1.0.31.rpm) and installed it on CentOS 7 (rpm -i kafka-connect-spooldir-1.0.31.rpm). 

When I start the connect-standalone.sh, I am getting the following:

[root@kafka01 kafka-connect-spooldir]# /opt/kafka_2.11-1.0.0/bin/connect-standalone.sh connect-avro-docker-arda.properties CSVExample.properties
[2018-08-20 19:02:11,438] INFO Kafka Connect standalone worker initializing ... (org.apache.kafka.connect.cli.ConnectStandalone:65)
[2018-08-20 19:02:11,459] INFO WorkerInfo values:
        jvm.args = -Xmx256M, -XX:+UseG1GC, -XX:MaxGCPauseMillis=20, -XX:InitiatingHeapOccupancyPercent=35, -XX:+ExplicitGCInvokesConcurrent, -Djava.awt.headless=true, -Dcom.sun.management.jmxremote, -Dcom.sun.management.jmxremote.authenticate=false, -Dcom.sun.management.jmxremote.ssl=false, -Dkafka.logs.dir=/opt/kafka_2.11-1.0.0/bin/../logs, -Dlog4j.configuration=file:/opt/kafka_2.11-1.0.0/bin/../config/connect-log4j.properties
        jvm.spec = Oracle Corporation, OpenJDK 64-Bit Server VM, 1.8.0_161, 25.161-b14
        jvm.classpath = :/opt/kafka_2.11-1.0.0/bin/../libs/aopalliance-repackaged-2.5.0-b32.jar:/opt/kafka_2.11-1.0.0/bin/../libs/argparse4j-0.7.0.jar:/opt/kafka_2.11-1.0.0/bin/../libs/commons-lang3-3.5.jar:/opt/kafka_2.11-1.0.0/bin/../libs/connect-api-1.0.0.jar:/opt/kafka_2.11-1.0.0/bin/../libs/connect-file-1.0.0.jar:/opt/kafka_2.11-1.0.0/bin/../libs/connect-json-1.0.0.jar:/opt/kafka_2.11-1.0.0/bin/../libs/connect-runtime-1.0.0.jar:/opt/kafka_2.11-1.0.0/bin/../libs/connect-transforms-1.0.0.jar:/opt/kafka_2.11-1.0.0/bin/../libs/guava-20.0.jar:/opt/kafka_2.11-1.0.0/bin/../libs/hk2-api-2.5.0-b32.jar:/opt/kafka_2.11-1.0.0/bin/../libs/hk2-locator-2.5.0-b32.jar:/opt/kafka_2.11-1.0.0/bin/../libs/hk2-utils-2.5.0-b32.jar:/opt/kafka_2.11-1.0.0/bin/../libs/jackson-annotations-2.9.1.jar:/opt/kafka_2.11-1.0.0/bin/../libs/jackson-core-2.9.1.jar:/opt/kafka_2.11-1.0.0/bin/../libs/jackson-databind-2.9.1.jar:/opt/kafka_2.11-1.0.0/bin/../libs/jackson-jaxrs-base-2.9.1.jar:/opt/kafka_2.11-1.0.0/bin/../libs/jackson-jaxrs-json-provider-2.9.1.jar:/opt/kafka_2.11-1.0.0/bin/../libs/jackson-module-jaxb-annotations-2.9.1.jar:/opt/kafka_2.11-1.0.0/bin/../libs/javassist-3.20.0-GA.jar:/opt/kafka_2.11-1.0.0/bin/../libs/javassist-3.21.0-GA.jar:/opt/kafka_2.11-1.0.0/bin/../libs/javax.annotation-api-1.2.jar:/opt/kafka_2.11-1.0.0/bin/../libs/javax.inject-1.jar:/opt/kafka_2.11-1.0.0/bin/../libs/javax.inject-2.5.0-b32.jar:/opt/kafka_2.11-1.0.0/bin/../libs/javax.servlet-api-3.1.0.jar:/opt/kafka_2.11-1.0.0/bin/../libs/javax.ws.rs-api-2.0.1.jar:/opt/kafka_2.11-1.0.0/bin/../libs/jersey-client-2.25.1.jar:/opt/kafka_2.11-1.0.0/bin/../libs/jersey-common-2.25.1.jar:/opt/kafka_2.11-1.0.0/bin/../libs/jersey-container-servlet-2.25.1.jar:/opt/kafka_2.11-1.0.0/bin/../libs/jersey-container-servlet-core-2.25.1.jar:/opt/kafka_2.11-1.0.0/bin/../libs/jersey-guava-2.25.1.jar:/opt/kafka_2.11-1.0.0/bin/../libs/jersey-media-jaxb-2.25.1.jar:/opt/kafka_2.11-1.0.0/bin/../libs/jersey-server-2.25.1.jar:/opt/kafka_2.11-1.0.0/bin/../libs/jetty-continuation-9.2.22.v20170606.jar:/opt/kafka_2.11-1.0.0/bin/../libs/jetty-http-9.2.22.v20170606.jar:/opt/kafka_2.11-1.0.0/bin/../libs/jetty-io-9.2.22.v20170606.jar:/opt/kafka_2.11-1.0.0/bin/../libs/jetty-security-9.2.22.v20170606.jar:/opt/kafka_2.11-1.0.0/bin/../libs/jetty-server-9.2.22.v20170606.jar:/opt/kafka_2.11-1.0.0/bin/../libs/jetty-servlet-9.2.22.v20170606.jar:/opt/kafka_2.11-1.0.0/bin/../libs/jetty-servlets-9.2.22.v20170606.jar:/opt/kafka_2.11-1.0.0/bin/../libs/jetty-util-9.2.22.v20170606.jar:/opt/kafka_2.11-1.0.0/bin/../libs/jopt-simple-5.0.4.jar:/opt/kafka_2.11-1.0.0/bin/../libs/kafka_2.11-1.0.0.jar:/opt/kafka_2.11-1.0.0/bin/../libs/kafka_2.11-1.0.0-sources.jar:/opt/kafka_2.11-1.0.0/bin/../libs/kafka_2.11-1.0.0-test-sources.jar:/opt/kafka_2.11-1.0.0/bin/../libs/kafka-clients-1.0.0.jar:/opt/kafka_2.11-1.0.0/bin/../libs/kafka-log4j-appender-1.0.0.jar:/opt/kafka_2.11-1.0.0/bin/../libs/kafka-streams-1.0.0.jar:/opt/kafka_2.11-1.0.0/bin/../libs/kafka-streams-examples-1.0.0.jar:/opt/kafka_2.11-1.0.0/bin/../libs/kafka-tools-1.0.0.jar:/opt/kafka_2.11-1.0.0/bin/../libs/log4j-1.2.17.jar:/opt/kafka_2.11-1.0.0/bin/../libs/lz4-java-1.4.jar:/opt/kafka_2.11-1.0.0/bin/../libs/maven-artifact-3.5.0.jar:/opt/kafka_2.11-1.0.0/bin/../libs/metrics-core-2.2.0.jar:/opt/kafka_2.11-1.0.0/bin/../libs/osgi-resource-locator-1.0.1.jar:/opt/kafka_2.11-1.0.0/bin/../libs/plexus-utils-3.0.24.jar:/opt/kafka_2.11-1.0.0/bin/../libs/reflections-0.9.11.jar:/opt/kafka_2.11-1.0.0/bin/../libs/rocksdbjni-5.7.3.jar:/opt/kafka_2.11-1.0.0/bin/../libs/scala-library-2.11.11.jar:/opt/kafka_2.11-1.0.0/bin/../libs/slf4j-api-1.7.25.jar:/opt/kafka_2.11-1.0.0/bin/../libs/slf4j-log4j12-1.7.25.jar:/opt/kafka_2.11-1.0.0/bin/../libs/snappy-java-1.1.4.jar:/opt/kafka_2.11-1.0.0/bin/../libs/validation-api-1.1.0.Final.jar:/opt/kafka_2.11-1.0.0/bin/../libs/zkclient-0.10.jar:/opt/kafka_2.11-1.0.0/bin/../libs/zookeeper-3.4.10.jar
        os.spec = Linux, amd64, 3.10.0-693.11.6.el7.x86_64
        os.vcpus = 2
 (org.apache.kafka.connect.runtime.WorkerInfo:71)
[2018-08-20 19:02:11,460] INFO Scanning for plugin classes. This might take a moment ... (org.apache.kafka.connect.cli.ConnectStandalone:74)
[2018-08-20 19:02:11,482] INFO Loading plugin from: /usr/share/kafka-connect/kafka-connect-spooldir/annotations-2.0.1.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:179)
[2018-08-20 19:02:11,667] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/share/kafka-connect/kafka-connect-spooldir/annotations-2.0.1.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:202)
[2018-08-20 19:02:11,669] INFO Loading plugin from: /usr/share/kafka-connect/kafka-connect-spooldir/commons-beanutils-1.9.3.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:179)
[2018-08-20 19:02:11,744] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/share/kafka-connect/kafka-connect-spooldir/commons-beanutils-1.9.3.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:202)
[2018-08-20 19:02:11,744] INFO Loading plugin from: /usr/share/kafka-connect/kafka-connect-spooldir/commons-collections-3.2.2.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:179)
[2018-08-20 19:02:11,891] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/share/kafka-connect/kafka-connect-spooldir/commons-collections-3.2.2.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:202)
[2018-08-20 19:02:11,893] INFO Loading plugin from: /usr/share/kafka-connect/kafka-connect-spooldir/commons-compress-1.16.1.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:179)
[2018-08-20 19:02:11,971] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/share/kafka-connect/kafka-connect-spooldir/commons-compress-1.16.1.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:202)
[2018-08-20 19:02:11,972] INFO Loading plugin from: /usr/share/kafka-connect/kafka-connect-spooldir/commons-lang3-3.5.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:179)
[2018-08-20 19:02:12,033] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/share/kafka-connect/kafka-connect-spooldir/commons-lang3-3.5.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:202)
[2018-08-20 19:02:12,034] INFO Loading plugin from: /usr/share/kafka-connect/kafka-connect-spooldir/commons-logging-1.2.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:179)
[2018-08-20 19:02:12,042] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/share/kafka-connect/kafka-connect-spooldir/commons-logging-1.2.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:202)
[2018-08-20 19:02:12,043] INFO Loading plugin from: /usr/share/kafka-connect/kafka-connect-spooldir/connect-utils-0.3.114.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:179)
[2018-08-20 19:02:12,066] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/share/kafka-connect/kafka-connect-spooldir/connect-utils-0.3.114.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:202)
[2018-08-20 19:02:12,067] INFO Loading plugin from: /usr/share/kafka-connect/kafka-connect-spooldir/extended-log-format-0.0.1.5.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:179)
[2018-08-20 19:02:12,072] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/share/kafka-connect/kafka-connect-spooldir/extended-log-format-0.0.1.5.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:202)
[2018-08-20 19:02:12,072] INFO Loading plugin from: /usr/share/kafka-connect/kafka-connect-spooldir/freemarker-2.3.25-incubating.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:179)
[2018-08-20 19:02:12,263] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/share/kafka-connect/kafka-connect-spooldir/freemarker-2.3.25-incubating.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:202)
[2018-08-20 19:02:12,265] INFO Loading plugin from: /usr/share/kafka-connect/kafka-connect-spooldir/guava-18.0.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:179)
[2018-08-20 19:02:12,545] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/share/kafka-connect/kafka-connect-spooldir/guava-18.0.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:202)
[2018-08-20 19:02:12,546] INFO Loading plugin from: /usr/share/kafka-connect/kafka-connect-spooldir/jackson-annotations-2.8.0.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:179)
[2018-08-20 19:02:12,557] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/share/kafka-connect/kafka-connect-spooldir/jackson-annotations-2.8.0.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:202)
[2018-08-20 19:02:12,558] INFO Loading plugin from: /usr/share/kafka-connect/kafka-connect-spooldir/jackson-core-2.8.5.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:179)
[2018-08-20 19:02:12,589] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/share/kafka-connect/kafka-connect-spooldir/jackson-core-2.8.5.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:202)
[2018-08-20 19:02:12,590] INFO Loading plugin from: /usr/share/kafka-connect/kafka-connect-spooldir/jackson-databind-2.8.5.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:179)
[2018-08-20 19:02:12,727] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/share/kafka-connect/kafka-connect-spooldir/jackson-databind-2.8.5.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:202)
[2018-08-20 19:02:12,734] INFO Loading plugin from: /usr/share/kafka-connect/kafka-connect-spooldir/javassist-3.19.0-GA.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:179)
[2018-08-20 19:02:12,814] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/share/kafka-connect/kafka-connect-spooldir/javassist-3.19.0-GA.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:202)
[2018-08-20 19:02:12,815] INFO Loading plugin from: /usr/share/kafka-connect/kafka-connect-spooldir/kafka-connect-spooldir-1.0.31.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:179)
Exception in thread "main" java.lang.NoClassDefFoundError: com/github/jcustenborder/kafka/connect/utils/VersionUtil
        at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirSourceConnector.version(SpoolDirSourceConnector.java:51)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.getPluginDesc(DelegatingClassLoader.java:279)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanPluginPath(DelegatingClassLoader.java:260)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanUrlsAndAddPlugins(DelegatingClassLoader.java:201)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.registerPlugin(DelegatingClassLoader.java:193)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initLoaders(DelegatingClassLoader.java:153)
        at org.apache.kafka.connect.runtime.isolation.Plugins.<init>(Plugins.java:47)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:75)
Caused by: java.lang.ClassNotFoundException: com.github.jcustenborder.kafka.connect.utils.VersionUtil
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:62)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 8 more

Are there any dependencies or settings that I might be missing?

Thanks in advance.

**Comment by eksantrik** [comment]
The reason I chose this way is that I received a bunch of failures when I downloaded the source code from git (git clone https://github.com/jcustenborder/kafka-connect-spooldir.git) and executed "mvn clean package".

**Comment by jcustenborder** [comment]
The best advice I can give you is to install your connectors to a centralized place and use plugin path to load them. My rpms install to `/usr/share/kafka-connect` and you can configure `plugin.path` to load from there. If you are building for source you need to make sure all of the dependencies are deployed as well.

**Comment by mammenj** [comment]
I had similar issue but my question is should'nt the mvn build pull in all the dependencies? or is there another project to build with dependencies?

**Comment by jcustenborder** [comment]
@mammenj `mvn clean package` is what you are looking for. During the `package` phase it gathers all of the dependencies and places them in the target. Look in `target/kafka-connect-target/`. It also creates the package that is uploaded to the Confluent hub in `target/components/packages/`.
