### ISSUE TITLE
Test failing when building

### ISSUE THREAD

**Issue by Guru107** [jcustenborder/kafka-connect-spooldir#69]
I ran `mvn clean package` after adding these dependencies in `pom.xml`

``` 
<dependency>
      <groupId>org.apache.kafka</groupId>
      <artifactId>connect-api</artifactId>
     <version>2.0.0</version>
</dependency>
<dependency>
     <groupId>org.apache.kafka</groupId>
     <artifactId>connect-transforms</artifactId>
     <version>2.0.0</version>
</dependency>
```
But test failed, and got this error.

```
20:13:12.578 [main] INFO  com.github.jcustenborder.kafka.connect.spooldir.SpoolDirSourceConnector - Setting key.schema to {
  "name" : "com.github.jcustenborder.kafka.connect.model.Key",
  "type" : "STRUCT",
  "isOptional" : false,
  "fieldSchemas" : { }
}
20:13:12.578 [main] INFO  com.github.jcustenborder.kafka.connect.spooldir.SpoolDirSourceConnector - Setting value.schema to {
  "name" : "com.github.jcustenborder.kafka.connect.model.Value",
  "type" : "STRUCT",
  "isOptional" : false,
  "fieldSchemas" : {
    "id" : {
      "type" : "STRING",
      "isOptional" : true
    },
    "first_name" : {
      "type" : "STRING",
      "isOptional" : true
    },
    "last_name" : {
      "type" : "STRING",
      "isOptional" : true
    },
    "email" : {
      "type" : "STRING",
      "isOptional" : true
    },
    "gender" : {
      "type" : "STRING",
      "isOptional" : true
    },
    "ip_address" : {
      "type" : "STRING",
      "isOptional" : true
    },
    "last_login" : {
      "type" : "STRING",
      "isOptional" : true
    },
    "account_balance" : {
      "type" : "STRING",
      "isOptional" : true
    },
    "country" : {
      "type" : "STRING",
      "isOptional" : true
    },
    "favorite_color" : {
      "type" : "STRING",
      "isOptional" : true
    }
  }
}
20:13:12.579 [main] TRACE com.github.jcustenborder.kafka.connect.spooldir.SpoolDirSourceConnectorTest - cleanupTempDir() - Removing /var/folders/4l/njkp363s3_gg670bmhwcdvhh0000gp/T/1541515392571-0/input/input0.json
20:13:12.579 [main] TRACE com.github.jcustenborder.kafka.connect.spooldir.SpoolDirSourceConnectorTest - cleanupTempDir() - Removing /var/folders/4l/njkp363s3_gg670bmhwcdvhh0000gp/T/1541515392571-0/input/input1.json
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.038 sec - in com.github.jcustenborder.kafka.connect.spooldir.SpoolDirJsonSourceConnectorTest
Running com.github.jcustenborder.kafka.connect.spooldir.SpoolDirJsonSourceTaskTest
20:13:12.588 [main] TRACE com.github.jcustenborder.kafka.connect.spooldir.SpoolDirSourceTaskTest - packagePrefix = com.github.jcustenborder.kafka.connect.spooldir.json
20:13:12.589 [main] INFO  com.github.jcustenborder.kafka.connect.spooldir.TestDataUtils - packageName = com.github.jcustenborder.kafka.connect.spooldir.json
20:13:12.596 [main] INFO  org.reflections.Reflections - Reflections took 7 ms to scan 1 urls, producing 10 keys and 10 values
20:13:12.598 [main] TRACE com.github.jcustenborder.kafka.connect.spooldir.TestDataUtils - Loading resource com/github/jcustenborder/kafka/connect/spooldir/json/FileModeFieldFieldsMatch.json
20:13:12.603 [main] ERROR com.github.jcustenborder.kafka.connect.spooldir.TestDataUtils - Exception thrown while loading /com/github/jcustenborder/kafka/connect/spooldir/json/FileModeFieldFieldsMatch.json
com.fasterxml.jackson.databind.JsonMappingException: field cannot be null. (through reference chain: com.github.jcustenborder.kafka.connect.spooldir.TestCase["expected"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:388)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:360)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:308)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:108)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2908)
	at com.github.jcustenborder.kafka.connect.spooldir.TestDataUtils.loadJsonResourceFiles(TestDataUtils.java:53)
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirSourceTaskTest.loadTestCases(SpoolDirSourceTaskTest.java:162)
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirJsonSourceTaskTest.poll(SpoolDirJsonSourceTaskTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:389)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptor.lambda$invokeTestMethod$1(TestFactoryTestDescriptor.java:70)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptor.invokeTestMethod(TestFactoryTestDescriptor.java:68)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:110)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:83)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$null$2(HierarchicalTestExecutor.java:92)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:92)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$null$2(HierarchicalTestExecutor.java:92)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:92)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:51)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invokeSingleClass(JUnitPlatformProvider.java:144)
	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:126)
	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:105)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: org.apache.kafka.connect.errors.DataException: field cannot be null.
	at org.apache.kafka.connect.data.Struct.put(Struct.java:215)
	at com.github.jcustenborder.kafka.connect.utils.jackson.ValueHelper.value(ValueHelper.java:197)
	at com.github.jcustenborder.kafka.connect.utils.jackson.SourceRecordSerializationModule$Storage.key(SourceRecordSerializationModule.java:65)
	at com.github.jcustenborder.kafka.connect.utils.jackson.SourceRecordSerializationModule$Storage.build(SourceRecordSerializationModule.java:79)
	at com.github.jcustenborder.kafka.connect.utils.jackson.SourceRecordSerializationModule$Deserializer.deserialize(SourceRecordSerializationModule.java:120)
	at com.github.jcustenborder.kafka.connect.utils.jackson.SourceRecordSerializationModule$Deserializer.deserialize(SourceRecordSerializationModule.java:115)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287)
	... 64 common frames omitted
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.025 sec <<< FAILURE! - in com.github.jcustenborder.kafka.connect.spooldir.SpoolDirJsonSourceTaskTest
poll()  Time elapsed: 0.025 sec  <<< ERROR!
com.fasterxml.jackson.databind.JsonMappingException: field cannot be null. (through reference chain: com.github.jcustenborder.kafka.connect.spooldir.TestCase["expected"]->java.util.ArrayList[0])
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirJsonSourceTaskTest.poll(SpoolDirJsonSourceTaskTest.java:49)
Caused by: org.apache.kafka.connect.errors.DataException: field cannot be null.
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirJsonSourceTaskTest.poll(SpoolDirJsonSourceTaskTest.java:49)


Results :

Tests in error:
  SpoolDirCsvSourceTaskTest.poll:49->SpoolDirSourceTaskTest.loadTestCases:162 » JsonMapping
  SpoolDirJsonSourceTaskTest.poll:49->SpoolDirSourceTaskTest.loadTestCases:162 » JsonMapping

Tests run: 48, Failures: 0, Errors: 2, Skipped: 0

```

I wasn't sure what needed to be changed here. Let me know where it needs fixing, I can work on it.

**Comment by rahulx411** [comment]
env: RHEL 7.4; confluent Kafka 5.0.1:

Getting the same errors as above while running  mvn clean package. 
Pl. advise.
```
Results :
Tests in error:
  SpoolDirCsvSourceTaskTest.poll:49->SpoolDirSourceTaskTest.loadTestCases:162 » JsonMapping
  SpoolDirJsonSourceTaskTest.poll:49->SpoolDirSourceTaskTest.loadTestCases:162 » JsonMapping

Tests run: 48, Failures: 0, Errors: 2, Skipped: 0
```

**Comment by Odyno** [comment]
The same error with the following configuration :
* Code Tag: 1.0.31  + Missing Dependecy 
* Apache Kafka (2.11) 0.10.2.2 
* Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T18:41:47Z)
* Java version: 1.8.0_171, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
* Default locale: en, platform encoding: UTF-8
* OS name: "linux", version: "4.15.0-39-generic", arch: "amd64", family: "unix"
* Using: mvn -X clean package
