### ISSUE TITLE
csv.separator.char=0 does not work

### ISSUE THREAD

**Issue by lhoshid** [jcustenborder/kafka-connect-spooldir#77]
Hi, 
I can successfully use the kafka-connect-spooldir when there is a comma used as the field delimiter (default), a pipe used as a field delimiter (where ACSII value 124) etc to read files.  When I try to use the connector to read a file which has a NUL field delimiter (e.g. the ASCII for NULL is: 0) as the cvs.separator.char, I get a java null pointer exception.    I have a file with Java Null characters which are used as a separator/field delimiter.
Thus,
e.g. csv.separator.char=124  (pipe field delimiter) works but csv.separator.char=0 does not work.
Can this be fixed to handle NUL (“\x00” - ASCII = 0 ) field delimiters?
Thanks!

**Comment by jcustenborder** [comment]
Can you give me a stack trace?

**Comment by lhoshid** [comment]
Hi Jeremy, I get an NullPointerException.  Thanks!  Lisa
[cid:image002.png@01D4D294.332A4CF0]

**Comment by lhoshid** [comment]
Hey Jeremy, please let me know if you need any other info!  Thanks!  Lisa

From: Hoshida, Lisa
Sent: Monday, March 4, 2019 2:12 PM
To: 'jcustenborder/kafka-connect-spooldir' <reply@reply.github.com>; jcustenborder/kafka-connect-spooldir <kafka-connect-spooldir@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [jcustenborder/kafka-connect-spooldir] csv.separator.char=0 does not work (#77)

Hi Jeremy, I get an NullPointerException.  Thanks!  Lisa
[cid:image001.png@01D4DA3C.E8BDE900]

**Comment by jcustenborder** [comment]
The callstack didn't come through but I think I have a repro. Does this look like the callstack?
```
java.lang.UnsupportedOperationException: The separator character must be defined!
	at com.opencsv.CSVParser.<init>(CSVParser.java:205)
	at com.opencsv.CSVParserBuilder.build(CSVParserBuilder.java:138)
```

**Comment by lhoshid** [comment]
Hi Jeremy, copied the error and pasted in this email below since the screen shot did not come thru.
FYI – I do have the csv.separator.char=0 defined in the connector.class=com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector so I do not get the error you sent below.

  *   Here is an example of the null separator in the input file [cid:image002.png@01D4DA52.82AB39E0]

Here is the Error I get:  [2019-03-14 10:35:50,780] ERROR WorkerSourceTask{id=CsvSpoolDir-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:177)
java.lang.NullPointerException
        at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceTask.recordOffset(SpoolDirCsvSourceTask.java:91)
        at com.github.jcustenborder.kafka.connect.spooldir.AbstractSourceTask.read(AbstractSourceTask.java:269)
        at com.github.jcustenborder.kafka.connect.spooldir.AbstractSourceTask.poll(AbstractSourceTask.java:144)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:244)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:220)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2019-03-14 10:35:50,782] ERROR WorkerSourceTask{id=CsvSpoolDir-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:178)
[2019-03-14 10:35:50,782] INFO [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 30000 ms. (org.apache.kafka.clients.producer.KafkaProducer:1136)I did define the character separator as:  csv.separator.char=0

The connector stops working and the file is stuck in a .PROCESSING status.

Thanks!
Lisa

**Comment by lhoshid** [comment]
Thank you!  looks like it is working!  Will test some more.  Lisa
