### ISSUE TITLE
Start connect failed with class not found

### ISSUE THREAD

**Issue by datafibers** [jcustenborder/kafka-connect-spooldir#9]
java 1.8 conflent 3.0.0

ERROR Error while starting connector CsvSpoolDir (org.apache.kafka.connect.runtime.WorkerConnector:109)
java.lang.NoClassDefFoundError: com/opencsv/enums/CSVReaderNullFieldIndicator
        at io.confluent.kafka.connect.source.SpoolDirectoryConfig.<clinit>(SpoolDirectoryConfig.java:124)
        at io.confluent.kafka.connect.source.SpoolDirectoryConnector.start(SpoolDirectoryConnector.java:40)
        at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:101)
        at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:126)
        at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:183)
        at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:178)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.startConnector(StandaloneHerder.java:250)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:164)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:94)
Caused by: java.lang.ClassNotFoundException: com.opencsv.enums.CSVReaderNullFieldIndicator
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 9 more

**Comment by jcustenborder** [comment]
Hi @datafibers!

Sorry about the issue. Did you download just the .jar or did you use the tar.gz? I need to remove the .jar from the releases since it only the output. I checked the .tar.gz and it does have opencsv-3.8.jar in the output. Can you confirm you have this in your classpath?

**Comment by gregroberti** [comment]
I ran into this issue as well, however, I resolved it by copying opencsv-3.8.jar and connect-utils-0.1.15.jar to the classpath as @jcustenborder had suggested. I think you can close this issue.

**Comment by jcustenborder** [comment]
@gregroberti how are you deploying this? Are you building locally or are you using the installation package I upload? If you are building locally, use `mvn clean package` and copy contents of target//kafka-connect-spooldir-1.0-SNAPSHOT-package. It will contain everything.

**Comment by gregroberti** [comment]
Yes, I'm building it locally with `mvn clean package` to run in a docker container. I found that I only need the following lines in my Dockerfile:

COPY kafka-connect-spooldir-1.0-SNAPSHOT.jar /etc/kafka-connect/jars
COPY opencsv-3.8.jar /etc/kafka-connect/jars
COPY connect-utils-0.1.15.jar /etc/kafka-connect/jars

For some reason I found that I didn't need the other jar files produced in the target directory.
